# Generated by Django 3.2.16 on 2025-08-10 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Низкий', max_length=56, verbose_name='Приолритет задачи')),
            ],
            options={
                'verbose_name': 'Приоритет задачи',
                'verbose_name_plural': 'Приоритеты задачи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название задачи', max_length=256, verbose_name='Название задачи')),
                ('comment', models.TextField(blank=True, help_text='Напиште комментарий к задаче, если это нужно.', verbose_name='Комментарий к задаче')),
                ('completed', models.BooleanField(default=False, help_text='Статус выполнения задачи', verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('finish_at', models.DateTimeField(help_text='Укажите срок выполнения задачи', verbose_name='Срок выполнения задачи')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('prioroty', models.ForeignKey(blank=True, help_text='Выберите приоритет задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priorities', to='tasks.prioritytask', verbose_name='Приоритет задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('created_at', '-completed'),
            },
        ),
    ]
