# Generated by Django 3.2.16 on 2025-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_at',
            field=models.DateTimeField(blank=True, help_text='Укажите срок выполнения задачи', null=True, verbose_name='Срок выполнения задачи'),
        ),
    ]
