# Generated by Django 3.2.16 on 2025-08-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('created_at',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='prioroty',
            new_name='priority',
        ),
    ]
