# Generated by Django 4.2 on 2025-10-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created_at',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
